spring.application.name=literatura-catalogo
spring.datasource.url=jdbc:postgresql://localhost:5432/literatura
spring.datasource.username=postgres
spring.datasource.password=tu_passharon
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false